name: datahub_refinery_custom_config
version: 1.0.0
config-version: 2
profile: datahub_refinery_custom_config
quoting: { identifier: true }

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
  
models:
  datahub_refinery_custom_config:
    +persist_docs: { relation: true, columns: true }

    bronze:
      +database: "{{ target.name | upper }}_BRONZE_ADF"
      +materialized: table

    gold:
      +database: "{{ target.name | upper }}_GOLD_ADF"
      +materialized: incremental

    platinum:
      +database: "{{ target.name | upper }}_PLATINUM_ADF"
      +materialized: view

    +post_hook: [
        "{{ manage_governance() }}"
    ]

snapshots:
  datahub_refinery_custom_config:
    +persist_docs: { relation: true, columns: true }

    silver:
      +database: "{{ target.name | upper }}_SILVER_ADF"
      +transient: false

    +post_hook: [
        "{{ manage_governance() }}"
    ]