SELECT COLUMN_NAME, TAG_NAME FROM TABLE (
            DEV_PLATINUM_ADF.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS (
                'DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNBREVIEWS_VIEW"',
                'VIEW'
            )
        )
        WHERE LEVEL = 'COLUMN'
        ;