ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"
MODIFY COLUMN "comments"
    SET MASKING POLICY DEV_DBTGOVERN.POLICIES."COLUMN_VARCHAR_DYNAMIC_MASKING_POLICY"


    USING ("comments", "reviewer_name")                

;