USE ROLE ACCOUNTADMIN;

-- 1. Create database and schema for dbt governance
CREATE OR REPLACE DATABASE DEV_DBTGOVERN;
CREATE OR REPLACE SCHEMA DEV_DBTGOVERN.TAGS;
CREATE OR REPLACE SCHEMA DEV_DBTGOVERN.POLICIES;

-- 2. Create row access policies
CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.SPECIFIC_YEAR_ACCESS_POLICY_LANDING AS (date VARCHAR)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND YEAR(date:: DATE) = 2024 THEN TRUE
        ELSE FALSE
    END
;

CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.SPECIFIC_YEAR_ACCESS_POLICY AS (date DATE)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND YEAR(date) = 2024 THEN TRUE
        ELSE FALSE
    END
;

-- 3. Create dynamic masking policies
CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_NUMBER_MASKING_POLICY AS (pii_value NUMBER)
RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        ELSE -1
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_MASKING_POLICY AS (pii_value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        ELSE '*** COLUMN-MASKED ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY AS (pii_value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        ELSE '*** TAG-COLUMN-MASKED ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY AS (pii_value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        ELSE '*** TAG-TABLE-MASKED ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_COMMENT_CONDITIONAL_MASKING_POLICY AS (pii_value VARCHAR, name VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND LOWER(name) != 'steve' THEN pii_value
        ELSE '*** COMMENT-MASKED ***'
    END
;

-- 4. Create tag-based dynamic masking policies (COLUMN)
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN;
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN2;

ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN
SET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY
;

-- 5. Create tag-based dynamic masking policies (TABLE)
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE;
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE2;

ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE
SET MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY
;

-- 5. Usage
SELECT *
FROM TABLE(
  DEV_BRONZE_ADF.INFORMATION_SCHEMA.POLICY_REFERENCES(
    ref_entity_name  => 'DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"',
    ref_entity_domain => 'TABLE'
  )
)
WHERE POLICY_KIND = 'ROW_ACCESS_POLICY'
;

SELECT REF_COLUMN_NAME, POLICY_NAME
FROM TABLE(
  DEV_BRONZE_ADF.INFORMATION_SCHEMA.POLICY_REFERENCES(
    ref_entity_name  => 'DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"',
    ref_entity_domain => 'TABLE'
  )
)
WHERE POLICY_KIND = 'MASKING_POLICY' AND TAG_NAME IS NULL
;

SELECT TAG_NAME FROM TABLE(
    DEV_BRONZE_ADF.INFORMATION_SCHEMA.TAG_REFERENCES(
        'DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"',
        'TABLE'
    )
);