USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS DEV_DBTGOVERN;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.TAGS;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.POLICIES;

ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBListings" DROP ALL ROW ACCESS POLICIES;
ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBReviews" DROP ALL ROW ACCESS POLICIES;


CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.ROOMTYPE_ACCESS_POLICY
AS (room_type VARCHAR)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND LOWER(room_type) != 'private room' THEN TRUE
        ELSE FALSE
    END
;

CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.NEIGHBOURHOOD_ROOMTYPE_ACCESS_POLICY
AS (neighbourhood VARCHAR, room_type VARCHAR)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND LOWER(neighbourhood) IN ('westminster') AND LOWER(room_type) != 'private room' THEN TRUE
        ELSE FALSE
    END
;

CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.CURRENT_YEAR_ACCESS_POLICY
AS (date DATE)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND YEAR(date) = YEAR(CURRENT_DATE) THEN TRUE
        ELSE FALSE
    END
;

--select +path:models/bronze/airbnb/airbnb_bronze_listings.sql

ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBListings" ADD ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.NEIGHBOURHOOD_ROOMTYPE_ACCESS_POLICY
    ON("neighbourhood", "room_type");

ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBReviews" ADD ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.CURRENT_YEAR_ACCESS_POLICY
    ON("date");

USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

SELECT DISTINCT "neighbourhood", "room_type" FROM DEV_BRONZE_ADF.AIRBNB."AirBnBListings";

SELECT MIN("date"::DATE), MAX("date"::DATE) FROM DEV_LANDING_ADF.AIRBNB."AirBnBReviews" LIMIT 5;
SELECT MIN("date"), MAX("date") FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews" LIMIT 5;


SELECT * FROM DEV_GOLD_ADF.AIRBNB.DIM_AIRBNBLISTING_DETAILS;