USE ROLE ACCOUNTADMIN;

-- 1. Create database and schema for dbt governance
CREATE DATABASE IF NOT EXISTS DEV_DBTGOVERN;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.POLICIES;

-- 2. Remove existings policies
DROP SCHEMA IF EXISTS DEV_BRONZE_ADF.AIRBNB_RAP;

ALTER TABLE DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews" DROP ALL ROW ACCESS POLICIES;
ALTER TABLE DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews_v" DROP ALL ROW ACCESS POLICIES;
ALTER TABLE DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews_sv" DROP ALL ROW ACCESS POLICIES;
ALTER TABLE DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews_dt" DROP ALL ROW ACCESS POLICIES;


-- 3. Create policies
CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.ROOMTYPE_ACCESS_POLICY AS (room_type VARCHAR)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND LOWER(room_type) != 'private room' THEN TRUE
        ELSE FALSE
    END
;

CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.NEIGHBOURHOOD_ROOMTYPE_ACCESS_POLICY AS (neighbourhood VARCHAR, room_type VARCHAR)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND LOWER(neighbourhood) IN ('westminster') AND LOWER(room_type) != 'private room' THEN TRUE
        ELSE FALSE
    END
;

CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.CURRENT_YEAR_ACCESS_POLICY AS (date DATE)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND YEAR(date) = YEAR(CURRENT_DATE) THEN TRUE
        ELSE FALSE
    END
;

-- 4. Run dbt models
--select path:models/bronze/airbnb_rap

-- 5. Apply policies manually (for testing)
ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBListings" ADD ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.NEIGHBOURHOOD_ROOMTYPE_ACCESS_POLICY
    ON("neighbourhood", "room_type");

-- 6. Validate dbt models
USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

-- Test Tables
SELECT MIN("date"), MAX("date") FROM DEV_LANDING_ADF.AIRBNB."AirBnBReviews";              -- (No RAP)

SELECT MIN("date"), MAX("date") FROM DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews";           -- (table)
SELECT MIN("date"), MAX("date") FROM DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews_v";         -- (view)
SELECT MIN("date"), MAX("date") FROM DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews_sv";        -- (secure view)
SELECT MIN("date"), MAX("date") FROM DEV_BRONZE_ADF.AIRBNB_RAP."AirBnBReviews_dt";        -- (dynamic table)

-- ELT Tables
SELECT DISTINCT "neighbourhood", "room_type" FROM DEV_BRONZE_ADF.AIRBNB."AirBnBListings"; -- (table)
SELECT DISTINCT "neighbourhood", "room_type" FROM DEV_SILVER_ADF.AIRBNB."AirBnBListings"; -- (snapshot)
SELECT DISTINCT ROOM_TYPE FROM DEV_GOLD_ADF.AIRBNB.DIM_AIRBNBLISTING_DETAILS;             -- (incremental)

SELECT DISTINCT "neighbourhood", "room_type" FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews";  -- (table)
SELECT DISTINCT "neighbourhood", "room_type" FROM DEV_SILVER_ADF.AIRBNB."AirBnBReviews";  -- (snapshot)