USE ROLE ACCOUNTADMIN;

-- 1. Create database and schema for dbt governance
CREATE DATABASE IF NOT EXISTS DEV_DBTGOVERN;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.TAGS;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.POLICIES;

-- 2. Create row access policies
CREATE OR REPLACE ROW ACCESS POLICY DEV_DBTGOVERN.POLICIES.PREVIOUS_YEAR_LESS_REVIEW_ACCESS_POLICY AS (date DATE, review_count NUMBER)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND YEAR(date) = YEAR(CURRENT_DATE) - 1 AND review_count <= 10 THEN TRUE
        ELSE FALSE
    END
;

-- 3. Create dynamic masking policies
CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_NUMBER_MASKING_POLICY AS (pii_value NUMBER)
RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        ELSE -1
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_DYNAMIC_MASKING_POLICY AS (pii_value VARCHAR, name VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND LOWER(name) != 'steve' THEN pii_value
        ELSE '*** COLUMN-MASKED ***'
    END
;

-- 4. Create tag-based dynamic masking policies (COLUMN)
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN;
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN2;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY AS (value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN value
        ELSE '*** TAG-COLUMN-MASKED ***'
    END
;

ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN
SET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY
;

-- 5. Create tag-based dynamic masking policies (TABLE)

CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE;
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE2;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY AS (value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN value
        ELSE '*** TAG-TABLE-MASKED ***'
    END
;

ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE
SET MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY
;

-- 5. Usage
SELECT *
FROM TABLE(
  DEV_BRONZE_ADF.INFORMATION_SCHEMA.POLICY_REFERENCES(
    ref_entity_name  => 'DEV_BRONZE_ADF.AIRBNB."AirBnBListings"',
    ref_entity_domain => 'TABLE'
  )
)
WHERE POLICY_KIND = 'ROW_ACCESS_POLICY'
;

SELECT REF_COLUMN_NAME, POLICY_NAME
FROM TABLE(
  DEV_BRONZE_ADF.INFORMATION_SCHEMA.POLICY_REFERENCES(
    ref_entity_name  => 'DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"',
    ref_entity_domain => 'TABLE'
  )
)
WHERE POLICY_KIND = 'MASKING_POLICY' AND TAG_NAME IS NULL
;

SELECT TAG_NAME FROM TABLE(
    DEV_BRONZE_ADF.INFORMATION_SCHEMA.TAG_REFERENCES(
        'DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"',
        'TABLE'
    )
);