USE ROLE ACCOUNTADMIN;
DROP SCHEMA IF EXISTS DEV_BRONZE_ADF.AIRBNB_DMP;

-- 1. Create database and schema for dbt governance
CREATE DATABASE IF NOT EXISTS DEV_DBTGOVERN;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.TAGS;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.POLICIES;

-- 2. Cleanup tags and masking policy
DROP SCHEMA IF EXISTS DEV_BRONZE_ADF.AIRBNB_DMP;

ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN UNSET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY;
ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE UNSET MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY;

-- 3. Create tags & policies
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN;
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_MASKING_POLICY AS (value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN value
        ELSE '*** COLUMN-MASKED ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY AS (value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN value
        ELSE '*** TAG-COLUMN-MASKED ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY AS (value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN value
        ELSE '*** TAG-TABLE-MASKED ***'
    END
;

-- 4. Add policies with tags
ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN SET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY;
ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE SET MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY;

-- 5. Run dbt models
--select path:models/bronze/airbnb_dmp

-- 6. Apply policies manually (for testing)

ALTER TABLE DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBListings" MODIFY COLUMN "name"
SET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_MASKING_POLICY
    USING("name")
;

-- 7. Validate dbt models
USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

SELECT * FROM DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBListings" LIMIT 5;