USE ROLE ACCOUNTADMIN;

-- 1. Create database and schema for dbt governance
CREATE DATABASE IF NOT EXISTS DEV_DBTGOVERN;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.POLICIES;

-- 2. Cleanup tags and masking policy
DROP SCHEMA IF EXISTS DEV_BRONZE_ADF.AIRBNB_DMP;

-- 3. Create tags & policies
CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_NUMBER_MASKING_POLICY AS (pii_value NUMBER)
RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        ELSE -1
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_DYNAMIC_MASKING_POLICY AS (pii_value VARCHAR, name VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN pii_value
        WHEN CURRENT_ROLE() IN ('SYSADMIN') AND LOWER(name) != 'steve' THEN pii_value
        ELSE '*** COLUMN-MASKED ***'
    END
;

-- 4. . Run dbt models
--select path:models/bronze/airbnb_dmp
--select +path:snapshots/silver/airbnb_dmp/airbnb_dmp_silver_reviews.sql

-- 5. Apply policies manually (for testing)

ALTER TABLE DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBReviews_inc" MODIFY COLUMN "id"
SET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_NUMBER_MASKING_POLICY
;

ALTER TABLE DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBReviews_inc" MODIFY COLUMN "comments"
SET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_DYNAMIC_MASKING_POLICY
    USING("comments", "reviewer_name")
;

ALTER TABLE DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBReviews_inc" MODIFY COLUMN "id" UNSET MASKING POLICY;
ALTER TABLE DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBReviews_inc" MODIFY COLUMN "comments" UNSET MASKING POLICY;

DESC TABLE DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBReviews_inc";

-- 7. Validate dbt models
USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

SELECT * FROM DEV_BRONZE_ADF.AIRBNB_DMP."AirBnBReviews_inc"
WHERE LOWER("reviewer_name") IN ('steve', 'emma')
;
