USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

-- 1. Cleanup
DROP SCHEMA IF EXISTS DEV_BRONZE_ADF.AIRBNB;
DROP SCHEMA IF EXISTS DEV_SILVER_ADF.AIRBNB;
DROP SCHEMA IF EXISTS DEV_GOLD_ADF.AIRBNB;
DROP SCHEMA IF EXISTS DEV_PLATINUM_ADF.AIRBNB;

-- 2. Execute DBT model
--select +path:models/platinum/airbnb/airbnb_platinum_fact_reviews_rap_*
--select +path:models/platinum/airbnb/airbnb_platinum_fact_reviews_dmp_*
--select +path:models/platinum/airbnb/airbnb_platinum_fact_reviews_tag_column_*
--select +path:models/platinum/airbnb/airbnb_platinum_fact_reviews_tag_table_*

-- 3. Catalog mapping table
SELECT * FROM DEV_DBTGOVERN.CATALOG.ROW_ACCESS_POLICY_VIEW;
SELECT * FROM DEV_DBTGOVERN.CATALOG.MASKING_POLICY_VIEW;
SELECT * FROM DEV_DBTGOVERN.CATALOG.TAGS_ON_COLUMN_VIEW;
SELECT * FROM DEV_DBTGOVERN.CATALOG.TAGS_ON_OBJECT_VIEW;

-- 4. Validation
-- a) Row access policy
SELECT '1_landing'      AS context, COUNT(*), MIN("date"), MAX("date") FROM DEV_LANDING_ADF.AIRBNB."AirBnBReviews" UNION ALL
SELECT '2_bronze'       AS context, COUNT(*), MIN("date"), MAX("date") FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews_Rap" UNION ALL
SELECT '3_silver'       AS context, COUNT(*), MIN("date"), MAX("date") FROM DEV_SILVER_ADF.AIRBNB."AirBnBReviews_Rap" UNION ALL
SELECT '4_gold'         AS context, COUNT(*), MIN("DATE"), MAX("DATE") FROM DEV_GOLD_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_RAP" UNION ALL
SELECT '5_platinum_v'   AS context, COUNT(*), MIN("DATE"), MAX("DATE") FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_RAP_VIEW" UNION ALL
SELECT '6_platinum_sv'  AS context, COUNT(*), MIN("DATE"), MAX("DATE") FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_RAP_SVIEW" UNION ALL
SELECT '7_platinum_dt'  AS context, COUNT(*), MIN("DATE"), MAX("DATE") FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_RAP_DT" UNION ALL
SELECT '8_platinum_v2'  AS context, COUNT(*), MIN("DATE"), MAX("DATE") FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_RAP_VIEW2"
;
    
-- b) Dynamic masking policy (Standard & Conditional)
SELECT * FROM (SELECT '1_landing' AS context, "id"::VARCHAR AS "id", "reviewer_name", "comments" FROM DEV_LANDING_ADF.AIRBNB."AirBnBReviews" WHERE "reviewer_name" = 'Steve' LIMIT 1) UNION ALL
SELECT * FROM (SELECT '2_bronze' AS context, "id"::VARCHAR, "reviewer_name", "comments" FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews_Dmp" WHERE "reviewer_name" = 'Steve' LIMIT 1) UNION ALL
SELECT * FROM (SELECT '3_silver' AS context, "id"::VARCHAR, "reviewer_name", "comments" FROM DEV_SILVER_ADF.AIRBNB."AirBnBReviews_Dmp" WHERE "reviewer_name" = 'Steve' LIMIT 1) UNION ALL
SELECT * FROM (SELECT '4_gold' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_GOLD_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_DMP" WHERE "REVIEWER_NAME" = 'Steve' LIMIT 1) UNION ALL
SELECT * FROM (SELECT '5_platinum_v' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_DMP_VIEW" WHERE "REVIEWER_NAME" = 'Steve' LIMIT 1) UNION ALL
SELECT * FROM (SELECT '6_platinum_sv' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_DMP_SVIEW" WHERE "REVIEWER_NAME" = 'Steve' LIMIT 1) UNION ALL
SELECT * FROM (SELECT '7_platinum_dt' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_DMP_DT" WHERE "REVIEWER_NAME" = 'Steve' LIMIT 1) UNION ALL
SELECT * FROM (SELECT '8_platinum_v2' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_DMP_VIEW2" WHERE "REVIEWER_NAME" = 'Steve' LIMIT 1)
;


-- c) Tag-based dynamic masking policy (Column)
SELECT * FROM (SELECT '2_bronze' AS context, "id"::VARCHAR AS "id", "reviewer_name", "comments" FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews_TagColumn" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '3_silver' AS context, "id"::VARCHAR, "reviewer_name", "comments" FROM DEV_SILVER_ADF.AIRBNB."AirBnBReviews_TagColumn" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '4_gold' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_GOLD_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_COLUMN" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '5_platinum_v' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_COLUMN_VIEW" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '6_platinum_sv' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_COLUMN_SVIEW" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '7_platinum_dt' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_COLUMN_DT" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '8_platinum_v2' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_COLUMN_VIEW2" LIMIT 1)
;

-- d) Tag-based dynamic masking policy (Table)
SELECT * FROM (SELECT '2_bronze' AS context, "id"::VARCHAR AS "id", "reviewer_name", "comments" FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews_TagTable" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '3_silver' AS context, "id"::VARCHAR, "reviewer_name", "comments" FROM DEV_SILVER_ADF.AIRBNB."AirBnBReviews_TagTable" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '4_gold' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_GOLD_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_TABLE" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '5_platinum_v' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_TABLE_VIEW" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '6_platinum_sv' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_TABLE_SVIEW" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '7_platinum_dt' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_TABLE_DT" LIMIT 1) UNION ALL
SELECT * FROM (SELECT '8_platinum_v2' AS context, "ID"::VARCHAR, "REVIEWER_NAME", "COMMENTS" FROM DEV_PLATINUM_ADF.AIRBNB."FACT_AIRBNB_REVIEWS_TAG_TABLE_VIEW2" LIMIT 1)
;