USE ROLE ACCOUNTADMIN;

-- 1. Create database and schema for dbt governance
CREATE DATABASE IF NOT EXISTS DEV_DBTGOVERN;
CREATE SCHEMA IF NOT EXISTS DEV_DBTGOVERN.TAGS;

-- 2. Cleanup tags and masking policy
DROP SCHEMA IF EXISTS DEV_BRONZE_ADF.AIRBNB;

ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN UNSET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY;
ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE UNSET MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY;

-- 3. Create tags & policies
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN;
CREATE OR REPLACE TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY AS (value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN value
        ELSE '*** TAG-COLUMN-MASKED ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY AS (value VARCHAR)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN value
        ELSE '*** TAG-TABLE-MASKED ***'
    END
;

-- 4. Add policies with tags
ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN SET MASKING POLICY DEV_DBTGOVERN.POLICIES.COLUMN_VARCHAR_TAG_MASKING_POLICY;
ALTER TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE SET MASKING POLICY DEV_DBTGOVERN.POLICIES.TABLE_VARCHAR_TAG_MASKING_POLICY;

-- 5. Run dbt models
--select path:models/bronze/airbnb

-- 6. Set/Unset policies manually (for testing)
ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"
MODIFY COLUMN "reviewer_name_2"
SET TAG DEV_DBTGOVERN.TAGS.PII_TAG_COLUMN = 'c-name',
        DEV_DBTGOVERN.TAGS.PII_TAG_TABLE = 't-name'
;

ALTER TABLE DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"
MODIFY COLUMN "reviewer_name_2"
UNSET TAG DEV_DBTGOVERN.TAGS.PII_TAG_TABLE
;

-- 7. Validate policies
SELECT COLUMN_NAME, TAG_NAME FROM TABLE(
    DEV_BRONZE_ADF.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
        'DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"',
        'TABLE'
    )
)
WHERE LEVEL = 'COLUMN'
;

-- 8. Validate data
USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

SELECT * FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews"
WHERE "reviewer_name" = 'Ben'
LIMIT 5;