name: datahub_govern
version: 1.0.0
config-version: 2
profile: datahub_govern

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

seeds:
  datahub_govern:
    +persist_docs: { relation: true, columns: true }
    +database: "{{ target.name | upper }}_DBTGOVERN"
    +transient: false

models:
  datahub_govern:
    +persist_docs: { relation: true, columns: true }
    +database: "{{ target.name | upper }}_DBTGOVERN"
    +materialized: view