name: datahub_refinery
version: 1.0.0
config-version: 2
profile: datahub_refinery
quoting: { identifier: true }

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
  
models:
  datahub_refinery:
    +persist_docs: { relation: true, columns: true }
    +post-hook: [
      "{{ manage_access_policy() }}"
    ]
    
    bronze:
      +database: "{{ (target.name ~ '_BRONZE_ADF') | upper }}"
      +materialized: table

    gold:
      +database: "{{ (target.name ~ '_GOLD_ADF') | upper }}"
      +materialized: incremental

snapshots:
  datahub_refinery:
    +persist_docs: { relation: true, columns: true }
    +post-hook: [
      "{{ manage_access_policy() }}"
    ]

    silver:
      +database: "{{ (target.name ~ '_SILVER_ADF') | upper }}"